### PR TITLE
Add the default evaluator

### PR DESCRIPTION
**Pull request by Laremere**
TODO after this:
- Write a dockerfile and yaml.
- Add other first match components.
- Get first match running using this evaluator.

### CODE REVIEW

**Comment by sawagh** [comment]
The current PRs seems to indicate a flat hierarchy under the language folder - is that the plan? 
go/defaultevaluator
go/demoui
..

My concern is - it may get very hairy very soon. Say the tutorial will have a mmf, director, frontend that work together - and tutorial2 will have its own and so on and so forth (with their own install files?) Can we nest this in a more navigable hierarchy?

go/demo
go/tutorials
go/examples

and then under them we have folders for whatever content they have?

**Comment by sawagh** [comment]
Will the default evaluator live in this repo along with being in the core repo? 

I do have some concerns over completely moving default evaluator to a separate repo. given that it is a default plugin to the core components, we will likely have yaml in the core repo that will deploy this too. 

If we are having this here as well - because some e2e demo / tutorials may plug it into their install, that sounds good.

**Comment by Laremere** [comment]
Re- hierarchy:  I would like to try not adding hierarchy.  Once you do, it starts adding lots of questions of taxonomy.  If, after the repo has a bunch of folders there, there are too many thing and there is an obvious segmentation, I think it's reasonable to do sorting then.

Re-default evaluator living here vs in the main repo:  I'm not sure yet.  We definitely need a test evaluator, but the default evaluator seems very ecosystem oriented.  I think it's reasonable to for now put it in both places, see how it looks, then either remove this one, or hide the one in the main repo.

**Comment by Laremere** [comment]
Oh, also, re-hierarchy, I think it's reasonable to have a readme inside go/ that gives details on each sub folder.

**Comment by sawagh** [comment]
+1 on default evaluator living in both repos - till we really understand the experience of removing it from either, lets keep it that way.

As for hierarchy, I do see the benefits of creating a flat structure - but also, if there is a natural affinity between components (say tutorial components), may make sense for them to be grouped together. I set that it is hard to create one as we start - so lets give it till end of this release - and then revisit this.

I have some other questions here - around whether there will be a 'release' of artifacts and if not, how does the version supported of some of the components map to OM version? I ll prefer not to remove components from core till we have figured those out.

Lets add components here as we go but not remove anything from the core repo atleast till end of this release.

**Pull request merged**
